call out cpu and ram are only factors in cluster efficiency
kubecost/docs pull request #1070
Opened 2024-06-18 18:39 UTC by kwombach12

## Related issue #

## Proposed Changes

2024-06-19 18:12 UTC, thomasvn approved these changes

2024-06-20 12:24 UTC, chipzoller requested changes

2024-06-20 12:24 UTC, chipzoller commented on using-kubecost/navigating-the-kubecost-ui/efficiency-dashboard.md
> +The Kubernetes Efficiency Dashboard  introduced in Kubecost 2.3 is designed to give Kubecost users a powerful tool for identifying the wasted spend coming from the clusters, nodes, and workloads in y
```suggestion
The Kubernetes Efficiency Dashboard introduced in Kubecost 2.3 is designed to give Kubecost users a powerful tool for identifying the wasted spend coming from the clusters, nodes, and workloads in their Kubernetes environment.
```

2024-06-20 12:24 UTC, chipzoller commented on using-kubecost/navigating-the-kubecost-ui/efficiency-dashboard.md
> +These Efficiency Reports provides you with a single-pane of glass to understand your waste across all of your Kubernetes clusters. Particularly valuable is its ability to help  you understand and see
```suggestion
These Efficiency Reports provide users with a single pane of glass to understand waste across all of their Kubernetes clusters. Particularly valuable is its ability to help  users understand and see the cost of idle resources on a per-cluster basis in a multi-cluster federation.
```

2024-06-20 12:24 UTC, chipzoller commented on using-kubecost/navigating-the-kubecost-ui/efficiency-dashboard.md
> +- _**Cluster Efficiency**_ - The ratio of the cost of used resources to the total cost of all resources. (cost of resources used) / (total cost of resources). This is the efficiency metric presented
```suggestion
- _**Cluster Efficiency**_ - The ratio of the cost of used resources to the total cost of all resources. (cost of resources used) / (total cost of resources). This is the efficiency metric presented in the upper right-hand corner of the Overview page. **Note:** Today, 'Cluster Efficiency' only considers CPU and RAM in its calculations. GPU and Storage metrics will be factored into the efficiency calculation in a future release.
```

2024-06-20 14:07 UTC, chipzoller approved these changes

2024-06-20 14:07 UTC, merged