Add documentation for asset saved reports and cloud cost reports
kubecost/docs pull request #1098
Opened 2024-07-19 21:51 UTC by avrodrigues5

## Related Issue

https://kubecost.atlassian.net/browse/ENG-2510

## Proposed Changes
* Added filter options available in cloud cost API
* Document Asset saved and cloud cost saved reports

2024-07-20 04:01 UTC, srpomeroy requested changes
Do we support `chartDisplay` for Assets and Cloud Costs?
What about `stepSize` for Allocations and Assets?

We call out "_Resolution_ in the UI" in a few places. Does this mean step size?

2024-07-20 04:01 UTC, srpomeroy commented on apis/filters-api.md
> +* `accountID`
Category too?

```suggestion
* `accountID`
* `category`
```

2024-07-20 04:05 UTC, srpomeroy commented on using-kubecost/navigating-the-kubecost-ui/reports.md
> +  * `cluster`
```suggestion
  * `cluster`
  * `label` requires the following format: `label:<label_name>`
```

2024-07-20 04:05 UTC, srpomeroy commented on using-kubecost/navigating-the-kubecost-ui/reports.md
> +  * `provider`
```suggestion
  * `label` requires the following format: `label:<label_name>`
  * `provider`
```

2024-07-22 17:43 UTC, avrodrigues5 commented on using-kubecost/navigating-the-kubecost-ui/reports.md
> +  * `accountID`
Category validation was failing in Backend. Fixed it via PR https://github.com/kubecost/kubecost-cost-model/pull/2620. Merging the suggestion as category aggregation will work!

2024-07-22 17:45 UTC, avrodrigues5 commented
> Do we support `chartDisplay` for Assets and Cloud Costs? What about `stepSize` for Allocations and Assets?
>  At this time No

> We call out "_Resolution_ in the UI" in a few places. Does this mean step size?

Yes, it's right. Im keeping the same used name for both but it means step size.

2024-07-22 20:23 UTC, srpomeroy approved these changes

2024-07-23 16:05 UTC, merged