Severity defs
kubecost/docs pull request #1104
Opened 2024-07-30 19:58 UTC by mmurph3

## Related Issue

## Proposed Changes

2024-07-30 20:01 UTC, chipzoller requested changes

2024-07-30 20:01 UTC, chipzoller commented on troubleshooting/kubcost-severity-definitions.md
File is misnamed. Should be `kubecost-severity-definitions.md`.

2024-07-30 20:01 UTC, chipzoller commented on troubleshooting/kubcost-severity-definitions.md
> +A problem that severely impacts your use of the software in a production environment (such as loss of production data or in which your Kubecost instance is no longer functioning.
```suggestion
## p0 (urgent)

A problem that severely impacts your use of the software in a production environment (such as loss of production data or in which your Kubecost instance is no longer functioning. 
```

Headings and beginning paragraphs need to be separated by a single new line.

2024-08-29 20:55 UTC, chipzoller commented
@mmurph3, can you resolve conflicts?

2024-09-16 18:05 UTC, chipzoller commented
@mmurph3, final bump.

2024-09-20 17:35 UTC, thomasvn commented on using-kubecost/navigating-the-kubecost-ui/reports.md
> -Saved reports should then populate in your upgraded Kubecost version.
@mmurph3 Based on your observations, this is no longer an issue?

2024-09-20 17:36 UTC, thomasvn commented on troubleshooting/kubecost-severity-definitions.md
> + Opening a support case at support@kubecost.com or starting a thread in slack in your private slack channel (Enterprise customers only) can make it easier to share technical data, error messages, and
```suggestion
Opening a support case at support@kubecost.com or starting a thread in slack in your private slack channel (Enterprise customers only) can make it easier to share technical data, error messages, and system information with the Kubecost team. 
```

2024-10-09 15:39 UTC, chipzoller commented
Conflicts

2025-01-24 21:46 UTC, srpomeroy commented
Do we want to finalize the changes here? Or is this doc going to be moot with M&A work?

2025-02-07 12:44 UTC, chipzoller commented
We're either fixing this up and merging it or closing, @mmurph3. If nothing is done by 2/14 it will be closed.

2025-03-25 20:16 UTC, closed without merging