[ENG-2969] Turbonomic Integration & Savings APIs
kubecost/docs pull request #1157
Opened 2024-12-09 14:56 UTC by biancaburtoiu

## Related Issue
Closes https://kubecost.atlassian.net/browse/ENG-2969

## Proposed Changes

This PR introduces two new pages:
- Turbonomic Integrations: instructions on how to set up
- Turbonomic Savings APIs

2024-12-09 14:57 UTC, biancaburtoiu commented on apis/savings-apis/turbonomic-savings-apis.md
@kwombach12 Would definitely appreciate your feedback on the phrasing, as well as the level of detail in describing the behaviour of these APIs. Thank you!

2024-12-09 14:59 UTC, chipzoller requested changes
Thanks for adding this! Please add the respective entries to SUMMARY.md so they show in the site nav.

2024-12-09 15:02 UTC, biancaburtoiu commented on SUMMARY.md
@chipzoller See below

2024-12-09 15:20 UTC, biancaburtoiu commented on SUMMARY.md
I've set up a single page `Turbonomic Actions APIs` as the contents are pretty brief (I'm awaiting feedback on the level of detail we want to go into here) but I'm definitely open to creating individual pages for each of the 4 APIs available at the moment.

2024-12-09 15:27 UTC, chipzoller commented on SUMMARY.md
Not sure we need four separate pages but I do think at least one page focusing on the UI aspect of what the integration enables is in order.

2024-12-09 19:44 UTC, kwombach12 commented on SUMMARY.md
I agree.  I would go into a bit more detail for each of these actions as it relates to their functionality in the UI. I think you have it structure right -- one section for action -- i would just cover the UI as well as the API. I think screenshots for each card could be impactful. I wouldn't do more than a sentence or two for the UI of each card as I do think this UX will change quite a bit in the future.

2024-12-09 22:12 UTC, chipzoller commented
@biancaburtoiu, can you also target this towards the `v2.5` branch, please? Once merged there, I'll send one PR to pull all 2.5 docs into `main` and then update GitBook.

2024-12-10 15:04 UTC, biancaburtoiu commented on apis/savings-apis/turbonomic-savings-apis.md
@kwombach12 @chipzoller I've added screenshots of the individual cards and slightly tweaked the copies

2024-12-10 16:10 UTC, kwombach12 approved these changes
LGTM

2024-12-10 16:10 UTC, merged