Fix grammar
kubecost/docs pull request #140
Opened 2021-10-27 05:26 UTC by IvanCherepov

Fix multiple typos in the documentation.

2021-11-15 17:02 UTC, michaelmdresser requested changes
Thank you so much for this PR! Documentation quality is really important to us and it is a continuing battle to keep it all up-to-date and well-written. All the help we can get is appreciated. Do you have any recommendations for linting documentation PRs?

Three things about this PR:
- Our current primary branch for this repo is actually `main`, but we haven't yet made it the default in GitHub. If its possible to re-target this PR without breaking everything, I'd appreciate it if you could do so. Otherwise, we can merge into `master` and we'll handle getting these changes into `main`.
- Looks like you've got a couple of merge conflicts, probably because we took so long to review this. Sorry about that!
- I have a few small requests for rephrasing or not doing some edits. Let me know if those work out okay for you!

2021-11-20 03:56 UTC, IvanCherepov commented on alerts.md
> + 2. [Budget](#type-budget) -- sends an email and/or Slack alert when spending crosses a defined threshold
fixed

2021-11-20 03:58 UTC, IvanCherepov commented on multi-cloud.md
> +This document outlines how to set up cloud integration for accounts on multiple cloud providers, or multiple accounts on the same cloud provider. Multi-Cloud is an enterprise feature. This configurat
fixed

2021-11-20 04:01 UTC, IvanCherepov commented on allocation-api.md
> +The aggregated cost model API retrieves data similar to the Kubecost Allocation frontend view (e.g. cost by namespace, label, deployment, and more) and is available at the following endpoint:
:)

2021-11-20 05:55 UTC, IvanCherepov commented
@michaelmdresser You are welcome! Unfortunately, I don't know good git linter for PRs. Although I think I addressed all of your comments, rebase might take a lot of effort. Do you think it'll be a good idea to close this PR and start a new one from the correct branch?

2021-11-22 13:00 UTC, michaelmdresser approved these changes
This is perfect now @IvanCherepov, thank you so much for the contribution.

2021-11-22 13:00 UTC, merged