Events
kubecost/docs pull request #258
Opened 2022-06-03 18:26 UTC by nikovacevic

2022-06-03 21:47 UTC, AdamStack18 approved these changes
LGTM

2022-06-06 02:02 UTC, dwbrown2 reviewed
Looks great, just a couple questions inline! 

Also, would you plan to link this page from anywhere to make it discoverable by others?

2022-06-06 02:02 UTC, dwbrown2 commented on events.md
> +* `AllocationSetSavedEvent` describes a saved AllocationSet
did you consider going the next level of details on describing the verbs, e.g. save, load, aggregate? i like how simple this is, but when looking at save for example, i'd have question about what exactly this represents. is this save to disk? memory? would backup influence this?

2022-07-06 17:24 UTC, srpomeroy requested changes
Two minor tweaks (and one suggestion) based on our markdown guide.

2022-07-06 17:24 UTC, srpomeroy commented on events.md
> +# Events
Titles need to be Setext H1 syntax I believe.
https://github.com/kubecost/docs/blob/main/markdown.md#titles

2022-07-06 17:24 UTC, srpomeroy commented on events.md
> +```
Though optional, I recommend adding language type to code block.
i.e.:
``` 
```json
```

2022-10-03 21:13 UTC, srpomeroy commented
@nikovacevic Is this PR still relevant?
I made some tweaks to the formatting to better support our current and future docs platform.

2022-10-04 18:37 UTC, dwbrown2 commented
Know Niko's out this week... I believe the rationale for creating this still make sense, but I'm sure some things have changed given all the core work going on here. 

Let me know if I can do more to help with docs migration while he's OOO.

2022-10-04 19:07 UTC, srpomeroy commented
Appreciate it @dwbrown2. We are trying to close out all non-release-related doc PRs by the end of next week.
It can wait until Niko is back unless you think someone else can answer quickly.

2022-10-07 16:51 UTC, dwbrown2 commented
@AjayTripathy are you familiar enough to say before Niko's back?

2022-10-12 16:45 UTC, nikovacevic commented
I'm back! Just bad at following up on my own docs PRs, apparently. I'll gladly accept whatever suggested changes are here, and can merge after that.

2022-10-12 16:48 UTC, nikovacevic commented on events.md
> +To access the most recent events in the event log, invoke `GET <kubecost>/model/etl/log`, which will provide the following, e.g.:
No configurability. Just 200 today. We can add configurability later, I think!

```go
eventLog:   NewEventLog(200),
```

2022-10-12 17:01 UTC, srpomeroy approved these changes
LGTM!

2022-10-12 17:03 UTC, merged