pv right sizing docs
kubecost/docs pull request #388
Opened 2022-10-12 22:28 UTC by nickcurie

2022-10-13 14:04 UTC, bstuder99 approved these changes
LGTM

2022-10-13 17:43 UTC, srpomeroy requested changes
Looks good @nickcurie.

One tweak for our docs platform.
Additionally, is this doc tied to v1.98 or can it be released now?

2022-10-13 17:43 UTC, srpomeroy commented on api-persistent-volume-right-sizing.md
> +```
Cna you please add the following metadata to the last line of the doc.
`<!--- {"article":"","section":"8454342470679","permissiongroup":"1500001277122"} --->`

2022-10-14 18:26 UTC, nickcurie commented
This is a v1.98 feature, so this doc should go out with that.

2022-10-14 18:43 UTC, srpomeroy approved these changes

2022-11-04 21:50 UTC, bstuder99 commented
Just checking in, we good to roll this out now?

2022-11-07 17:37 UTC, nickcurie commented
Yep, this is live in 1.98 now!

2022-11-07 18:17 UTC, merged