Update custom-prom.md
kubecost/docs pull request #583
Opened 2023-03-14 16:57 UTC by praveenkumar0566

Added Data Retention step

2023-03-14 17:03 UTC, srpomeroy requested changes

2023-03-14 17:03 UTC, srpomeroy commented on custom-prom.md
> +By default metric retention is 91 days, Howerver the retenion of data can be further increased with a configurable value for a property **etlDailyStoreDurationDays**
```suggestion
By default, metric retention is 91 days, however the retention of data can be further increased with a configurable value for a property **etlDailyStoreDurationDays**
```

2023-03-20 14:48 UTC, praveenkumar0566 commented
Hi @srpomeroy Is there anything i need to address to enable merge? I have added the review comments provided.

2023-03-20 14:53 UTC, bstuder99 approved these changes

2023-03-20 14:53 UTC, bstuder99 commented
Sorry, was watching over this last week but wasn't sure if it had been resolved. I can give out a review

2023-03-20 15:55 UTC, thomasvn commented
Thanks @praveenkumar0566 for getting started on this! This is a pretty important config.

@bstuder99 This config allows users to configure the amount of days Kubecost will serve via API and Frontend. The default is 90 days. Because this is a frequently asked about config, do you think it should eventually become a stand-alone doc under the "Advanced Configuration" section? We should also reference this config in the "Cost Allocation" and "Assets" doc.

2023-03-28 17:53 UTC, merged