Update gcp-out-of-cluster.md
kubecost/docs pull request #677
Opened 2023-06-21 16:52 UTC by srpomeroy

2023-06-21 19:25 UTC, bstuder99 requested changes
LGTM barring one comment

2023-06-21 19:25 UTC, bstuder99 commented on gcp-out-of-cluster.md
> +Once the GCP service account has been connected, you can set up the remaining configuration parameters.
A bit passive, would remove this change

2023-08-18 17:24 UTC, srpomeroy commented on gcp-out-of-cluster.md
> +Once the GCP service account has been connected, you can set up the remaining configuration parameters.
Fixed

2023-08-18 17:36 UTC, bstuder99 approved these changes

2023-08-18 17:37 UTC, merged