Add new doc for the Grafana Mimir integration
kubecost/docs pull request #681
Opened 2023-06-29 22:27 UTC by linhlam-kc

Add new doc for the Grafana Mimir integration.

Related PR: https://github.com/kubecost/cost-analyzer-helm-chart/pull/2201

2023-06-29 22:35 UTC, srpomeroy commented
Should this be labeled for the next release (1.105) or is it available now in the published helm cart?

2023-06-30 17:51 UTC, bstuder99 requested changes

2023-06-30 20:33 UTC, linhlam-kc commented
@srpomeroy It should be in 1.105.0 . I see the code changes are included in 1.105.0-rc.3

2023-06-30 20:35 UTC, linhlam-kc commented on grafana-mimir-integration.md
> +In the standard deployment of [Kubecost](https://www.kubecost.com/), [Kubecost](https://www.kubecost.com/) is deployed with a bundled Prometheus instance to collect and store metrics of your Kubernet
Fixed in the latest commit.

2023-06-30 21:18 UTC, bstuder99 approved these changes

2023-07-17 14:33 UTC, merged