summary update
kubecost/docs pull request #706
Opened 2023-08-22 11:48 UTC by jessegoodier

1. Clean up summary
2. Fixes link on aws-cur-setup, spelling error

2023-08-22 12:55 UTC, chipzoller commented on SUMMARY.md
> +    * [Thanos Federation (fully supported)](thanos-setup.md)
Why the "fully supported" qualification here? Seems a bit odd for a document/page title in a product's official documentation.

2023-08-22 13:09 UTC, jessegoodier commented on thanos-setup.md
> +The *preferred* method for multi-cluster is [ETL Federation](federated-etl.md). The configuration guide below is for Kubecost Thanos Federation, which may not scale as well as ETL Federation in large
@chipzoller Can you take a look at these changes?

2023-08-22 13:13 UTC, chipzoller requested changes

2023-08-22 13:13 UTC, chipzoller commented on thanos-setup.md
> +Thanos is a tool to aggregate prometheus metrics to a central object storage (S3 compatible) bucket. Thanos is implemented as a sidecar on the Prometheus pod on all clusters.
"Prometheus" is a proper noun.

2023-08-22 13:13 UTC, chipzoller commented on thanos-setup.md
> +1. Follow steps [here](long-term-storage.md#option-b-out-of-cluster-storage-thanos) to enable all required Thanos components on a Kubecost Primary cluster, including the prometheus sidecar.
"Prometheus"

2023-08-22 13:13 UTC, chipzoller commented on thanos-setup.md
> +1. Follow steps [here](long-term-storage.md#option-b-out-of-cluster-storage-thanos) to enable all required Thanos components on a Kubecost Primary cluster, including the prometheus sidecar.
"primary"

2023-08-22 14:06 UTC, bstuder99 approved these changes

2023-08-23 15:48 UTC, chipzoller approved these changes

2023-08-23 15:48 UTC, merged