Updates Container Request Right Sizing API doc to remove GitBook glitched indents
kubecost/docs pull request #722
Opened 2023-09-18 20:43 UTC by bstuder99

Chip, I'm assigning you as a reviewer so you can see this repeated problem we've had with our API docs.

A while back I restructured our APIs using GitBook's API cell feature to better organize parameters, example outputs, and other details about our APIs. However, one repeated error I keep seeing in these docs is that it unnecessarily indents when it detects inline code or other style elements. This requires manual changes to fix it in the source file. I have raised the issue to GitBook, who sees the changes being made against the source code (even though we are not manually doing it), and they assume we're doing it on purpose even though this is clearly a bug. In case you see this behavior in our API doc, just wanted to let you know why it's happening, and to let me know.

This PR just updates this one doc, but I was hoping to get your thoughts on this before I continue making changes to a few other affected docs.

2023-09-18 20:46 UTC, bstuder99 commented
Other affected docs:
* https://docs.kubecost.com/apis/apis-overview/allocation-trends-api
* https://docs.kubecost.com/apis/apis-overview/cloud-cost-api
* https://docs.kubecost.com/apis/apis-overview/cost-events-audit-api

I'm going to go through the blame history of each of these and see if I can see what's going on

2023-09-18 20:48 UTC, bstuder99 commented
My findings currently are:
* These indents are applied almost immediately when the content is created in GitBook. No secondary PR/CR is rewriting it, which you can see in the history of this doc when I initially overhauled our API content.
* Changes have to be manually corrected in GitHub. Changing them in GitBook does not seem to have lasting effect.

2023-09-18 20:59 UTC, chipzoller commented
I do not use GitBook as an authoring or editing interface so I cannot explain what is happening, just simply making an observation that these are line breaks (not indentations) and occur when either a link is inserted or in-line code is formatted (not code blocks).

I'd be glad to hop on a screen sharing session where you can demonstrate how you're making this happen and then we can see if there's something we can do differently.

2023-09-18 21:03 UTC, bstuder99 commented
I'd hop on whenever, but I don't know how many answers I'll have for you. This seems like a reoccurring problem I have yet to solve.

2023-09-18 21:05 UTC, chipzoller requested changes

2023-09-18 21:05 UTC, chipzoller commented on api-request-right-sizing-v2.md
> +The desired quantile to base CPU recommendations on. Only used if `algorithmCPU=quantile`. **Note**: a quantile of `0.95`is the same as a 95th percentile.
Missing space separating \`0.95\` and "is".

2023-09-18 21:05 UTC, chipzoller commented on api-request-right-sizing-v2.md
> +Order to sort by. Default value `descending`. Options are `descending` and `ascending`.
"Defaults to" is the verbiage that has been established thus far. Suggest continuing to use it for consistency.

2023-09-18 21:06 UTC, chipzoller commented
> I'd hop on whenever, but I don't know how many answers I'll have for you. This seems like a reoccurring problem I have yet to solve.

Let me at least take a look and see. Contact me directly on Slack to sync up.

2023-09-19 19:45 UTC, chipzoller commented
As you address comments in a PR review, please click "Resolve conversation" to indicate to reviewers that those specific areas have been addressed.

2023-09-19 19:45 UTC, chipzoller approved these changes

2023-09-19 19:45 UTC, merged