Adds section to Fed ETL doc for when using internal CA
kubecost/docs pull request #810
Opened 2023-11-08 18:55 UTC by bstuder99

## Related issue #

## Proposed Changes

2023-11-13 22:18 UTC, bstuder99 commented
@mmurph3 Rewrote a couple commands, can you just review them to make sure it's all still correct?

2023-11-13 22:18 UTC, bstuder99 commented
Will still try to elaborate on what is meant by Federator agent as well

2023-11-14 20:38 UTC, mmurph3 submitted a review, later dismissed
lgtm

2023-11-14 20:52 UTC, chipzoller requested changes

2023-11-14 20:52 UTC, chipzoller commented on install-and-configure/install/multi-cluster/federated-etl/federated-etl.md
> +`kubectl create cm kubecost-federator-certs --from-kubecost-federator-certs.yaml=/path/to/kubecost-federator-certs`
Command is incorrect:

```suggestion
`kubectl create cm kubecost-federator-certs --from-file=/path/to/kubecost-federator-certs.yaml`
```

2023-11-14 20:52 UTC, chipzoller commented on install-and-configure/install/multi-cluster/federated-etl/federated-etl.md
> +```
```suggestion
```yaml
```

2023-11-14 20:52 UTC, chipzoller commented on install-and-configure/install/multi-cluster/federated-etl/federated-etl.md
> +```
```suggestion
```yaml
```

2023-11-14 20:52 UTC, chipzoller commented on install-and-configure/install/multi-cluster/federated-etl/federated-etl.md
> +```
```suggestion
```sh
```

2023-11-14 20:52 UTC, chipzoller commented on install-and-configure/install/multi-cluster/federated-etl/federated-etl.md
> +kubectl create namespace kubecost
This will fail if the `kubecost` Namespace already exists. Suggest either omitting or telling users as such.

2023-11-14 20:52 UTC, chipzoller commented on install-and-configure/install/multi-cluster/federated-etl/federated-etl.md
> +  --from-file federated-store.yaml
```suggestion
  --from-file=federated-store.yaml  
```

2023-11-14 21:01 UTC, bstuder99 commented
@chipzoller thanks for reviewing the code and issuing corrections

2023-11-14 21:04 UTC, chipzoller approved these changes
Forgot one fencing code syntax, otherwise good.

2023-11-14 21:04 UTC, chipzoller commented on install-and-configure/install/multi-cluster/federated-etl/federated-etl.md
> +```
```suggestion
```yaml
```

2023-11-14 21:10 UTC, merged